---
version: 0.17

languages:
    default: Sumerian
    Early Akkadian: akk-x-earakk
    Old Akkadian: akk-x-oldakk
    Ur III Akkadian: akk-x-ur3akk
    Old Assyrian: akk-x-oldass
    Old Babylonian: akk-x-oldbab
    Old Babylonian peripheral: akk-x-obperi
    Middle Assyrian: akk-x-midass
    Middle Babylonian: akk-x-midbab
    Middle Babylonian peripheral: akk-x-mbperi
    Neo-Assyrian: akk-x-neoass
    Neo-Babylonian: akk-x-neobab
    Late Babylonian: akk-x-ltebab
    Standard Babylonian: akk-x-stdbab
    Conventional Akkadian: akk-x-conakk
    Hittite: hit
    Sumerian: sux-x-emegir
    Emesal: sux-x-emesal
    Syllabic: sux-x-syllabic
    Udgalnun: sux-x-udgalnun

projects:
    default:
        - cams/gkab
    cams:
        - gkab
    cmawro:
    dcclt:
        - ebla
        - nineveh
        - obale
    etcsri:
    rimanum:
    rinap:
        - rinap1
        - rinap3
        - rinap4
        - senn2
        - sources
    saao:
        - saa01
        - saa02
        - saa03
        - saa04
        - saa05
        - saa06
        - saa07
        - saa08
        - saa09
        - saa10
        - saa11
        - saa12
        - saa13
        - saa14
        - saa15
        - saa16
        - saa17
        - saa18
        - saa19

protocols:
    - math
    - legacy
    - lexical
    - mylines

keystrokes:
    undo: VK_Z
    redo: VK_Y
    saveFile: VK_S
    saveAsFile: VK_E
    newFile: VK_N
    openFile: VK_O
    closeFile: VK_W
    validate: VK_D
    lemmatise: VK_L
    showHelp: VK_H
    splitEditorH: VK_PERIOD
    splitEditorV: VK_SEMICOLON
    find: VK_F
    syntax_highlight_switch: VK_T

find_keystrokes:
    find_next: VK_G
    replace_one: VK_R
    replace_all: VK_A

working_dir:
    default: None

servers:
    default: upenn
    munich:
        url: http://oracc.ub.uni-muenchen.de
        port: 8085
        dir: 'p'
    upenn:
        url: http://build-oracc.museum.upenn.edu
        port: 8085
        dir: 'p'

console_style:
    fontsize:
        default: 11
        user: 11
    background_color:
        default: Gray
        user: Gray
    font_color:
        default: Black
        user: Black

edit_area_style:
    fontsize:
        default: 14
        user: 14

new_user: True
