sudo: false

language: java

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk7
    - jdk: oraclejdk8
      env: PEP8=1

install:
    - |
    # Check if this is the PEP8 test instance and install pep8
    if [ -z "$PEP8" ]; then
      pip install pep8

script:
  # Check if this is the PEP8 test instance
  if [ -z "$PEP8" ]; then
    pip install pep8
    pep8 python/
  else
    mvn clean test
  fi
